name: onerainbow
favicon: null
layout_spectrum: 0.43600156577304006
typography_spectrum: 0.9947820685338229
title: one rainbow art and design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8d2e0'
    - '#65452a'
    - '#f75658'
    - '#0f0000'
    - '#009566'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
