name: onerainbow
favicon: null
layout_spectrum: 0.43600156577304006
typography_spectrum: 0.9947820685338229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.030274819349870086
  lightness: 0.10377453058026731
  saturation: 0.796914525795728
  rhythmicContrast: 0.23502592323347926
purpose: []
